"""Initial migration

Revision ID: 7746b5eac04b
Revises: 
Create Date: 2026-02-26 08:10:47.983593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7746b5eac04b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote_frango',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade_inicial', sa.BigInteger(), nullable=False),
    sa.Column('data_entrada_aves', sa.Date(), nullable=False),
    sa.Column('data_ninhada', sa.Date(), nullable=False),
    sa.Column('fornecedor', sa.String(length=100), nullable=False),
    sa.Column('tipo_lote', sa.String(length=20), nullable=False),
    sa.Column('galpao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('peso_medio', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_racao',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_racao', sa.String(length=30), nullable=False),
    sa.Column('fornecedor', sa.String(length=100), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('quilos', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_despesa',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('consumo_lote_diaria',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_lote_frango', sa.BigInteger(), nullable=False),
    sa.Column('id_lote_racao', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quilos', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['id_lote_frango'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_lote_racao'], ['lote_racao.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controle_vacinas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lote_frango', sa.BigInteger(), nullable=False),
    sa.Column('medicamento_aplicado', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('responsavel_aplicacao', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_lote_frango'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corte',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lote_frango', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['id_lote_frango'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesa',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_tipo_despesa', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_despesa'], ['tipo_despesa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortalidade',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lote_frango', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quantidade_mortes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote_frango'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postura',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lote_frango', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quantidade_ovos', sa.Integer(), nullable=False),
    sa.Column('ovos_descartados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote_frango'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda_corte',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lote_frango', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quilos', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['id_lote_frango'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda_ovos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_lote_frango', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantidade_ovos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote_frango'], ['lote_frango.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_ovos')
    op.drop_table('venda_corte')
    op.drop_table('postura')
    op.drop_table('mortalidade')
    op.drop_table('despesa')
    op.drop_table('corte')
    op.drop_table('controle_vacinas')
    op.drop_table('consumo_lote_diaria')
    op.drop_table('tipo_despesa')
    op.drop_table('lote_racao')
    op.drop_table('lote_frango')
    # ### end Alembic commands ###
